#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Final private Perl package names for the ordered-byte native layer. These are
# implementation concepts, not XS-generation terminology.
replacements = (
    ('Linux::Event::_ByteStream::XSDescriptor',
     'Linux::Event::_ByteStream::Descriptor::Native'),
    ('Linux::Event::_ByteStream::XSState',
     'Linux::Event::_ByteStream::State'),
    ('Linux::Event::IO::Sock::Stream::XSDescriptor',
     'Linux::Event::_ByteStream::Descriptor::Native'),
    ('Linux::Event::IO::Sock::Stream::XSState',
     'Linux::Event::_ByteStream::State'),
)

for base in (ROOT / 'lib', ROOT / 't', ROOT / 'bench', ROOT / 'xsbytestream'):
    if not base.exists():
        continue
    for p in base.rglob('*'):
        if not p.is_file() or p.suffix not in {'.pm', '.t', '.pl', '.xs', '.c', '.h', '.PL'}:
            continue
        text = p.read_text()
        for old, new in replacements:
            text = text.replace(old, new)
        # Class-level test-consumer constructors/destruction counters are test
        # support, not methods inherited by every public ordered-byte leaf.
        text = text.replace(
            'Linux::Event::_ByteStream->_test_consumer_',
            'Linux::Event::_ByteStream::TestSupport->_test_consumer_',
        )
        text = text.replace(
            'Linux::Event::IO::Sock::Stream->_test_consumer_',
            'Linux::Event::_ByteStream::TestSupport->_test_consumer_',
        )
        p.write_text(text)

# Move the class-level test helper XSUBs off the ordered-byte base. State-level
# test methods stay on _ByteStream::State because they operate on a native
# connection state object.
p = ROOT / 'xsbytestream/ByteStream.xs'
text = p.read_text()
marker = '\nSV *\n_test_consumer_definition(CLASS, variant = "valid")\n'
if marker in text and 'PACKAGE = Linux::Event::_ByteStream::TestSupport' not in text:
    text = text.replace(
        marker,
        '\nMODULE = Linux::Event::_ByteStream    PACKAGE = Linux::Event::_ByteStream::TestSupport\n'
        'PROTOTYPES: DISABLE\n'
        + marker,
        1,
    )
p.write_text(text)

# Makefile.PL's no_index list is generated by the structural pass and should
# describe the final private packages rather than intermediate XS names.
p = ROOT / 'Makefile.PL'
text = p.read_text()
text = text.replace(
    '                Linux::Event::_ByteStream::XSDescriptor\n',
    '                Linux::Event::_ByteStream::Descriptor::Native\n',
)
text = text.replace(
    '                Linux::Event::_ByteStream::XSState\n',
    '                Linux::Event::_ByteStream::State\n'
    '                Linux::Event::_ByteStream::TestSupport\n',
)
p.write_text(text)

print('coherent ordered-byte native names applied')
